tap "github/gh"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "koekeishiya/formulae"
tap "prakashdanish/formulae"
tap "schniz/tap"
brew "git-extras"
brew "hub"
brew "imagemagick"
brew "mysql@5.7", restart_service: true, link: true
brew "neovim"
brew "redis", restart_service: true
brew "youtube-dl"
brew "z"
brew "zsh-autosuggestions"
brew "schniz/tap/fnm"
cask "alacritty"
cask "aws-vault"
cask "iterm2"
cask "ngrok"
