tap "github/gh"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "schniz/tap"
brew "exiftool"
brew "git-extras"
brew "hub"
brew "mysql@5.7", restart_service: true, link: true
brew "redis", restart_service: true
brew "youtube-dl"
brew "z"
brew "zsh-autosuggestions"
brew "schniz/tap/fnm"
cask "alacritty"
cask "aws-vault"
cask "font-victor-mono"
cask "iterm2"
cask "qview"
